twig:
    default_path: '%kernel.project_dir%/src/Frontend/html'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    auto_reload: '%kernel.debug%'
