dist: xenial
sudo: false
language: php

php:
    - '7.3'

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APP_ENV=test
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio330
        - MINIO_BUCKET=test-bucket
        - SQL_MASTER=pgsql://postgres:@127.0.0.1:5432/test_db
        - SQL_SLAVES=pgsql://postgres:@127.0.0.1:5432/test_db
        - S3_DSN=http://minio:minio330@127.0.0.1:9000/test_region

services:
    - docker
    - postgresql

before_install:
    - docker run --name minio -d
        -p 9000:9000
        -e MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
        -e MINIO_SECRET_KEY=$MINIO_SECRET_KEY
        minio/minio server /data
    - docker run --rm
        --link minio
        --entrypoint sh
        minio/mc
        -c "
        mc config host add doop http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        && mc rm -r --force doop/$MINIO_BUCKET || true
        && mc mb doop/$MINIO_BUCKET
        && mc policy download doop/$MINIO_BUCKET
        "
    - psql -c "CREATE DATABASE test_db;" -U postgres
    - pecl channel-update pecl.php.net
    - yes | pecl install imagick

install:
    - composer validate  --no-interaction --strict
    - composer install --no-interaction --no-suggest

before_script: bin/console migrations:migrate --no-interaction

script:
    - vendor/bin/phpcs -ps
    - vendor/bin/phpunit --coverage-clover var/cache/clover.xml

after_success:
    - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - travis_retry php php-coveralls.phar -e test -x var/cache/clover.xml -o var/cache/coveralls.json
