dist: focal
sudo: false
language: php

php:
    - '7.4'
node_js:
    - 14

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache
        - $HOME/.yarn-cache
        - node_modules

env:
    global:
        - APP_ENV=test
        - SQL_MASTER=pgsql://postgres:@127.0.0.1:5432/test_db
        - SQL_SLAVES=pgsql://postgres:@127.0.0.1:5432/test_db
        - S3_ENDPOINT=http://127.0.0.1:9000
        - S3_KEY=minio
        - S3_SECRET=minio330
        - S3_REGION=eu-west-2
        - S3_BUCKET=test-bucket

services:
    - docker
    - postgresql

before_install:
    - docker run --name minio -d
        -p 9000:9000
        -e MINIO_ACCESS_KEY=$S3_KEY
        -e MINIO_SECRET_KEY=$S3_SECRET
        -e MINIO_REGION=$S3_REGION
        minio/minio server /data
    - docker run --rm
        --network host
        --entrypoint sh
        minio/mc
        -c "
        mc config host add doop $S3_ENDPOINT $S3_KEY $S3_SECRET
        && mc mb --region $S3_REGION --ignore-existing doop/$S3_BUCKET
        && mc policy set download doop/$S3_BUCKET
        "
    - phpenv config-rm xdebug.ini
    - nvm install 14
    - psql -c "CREATE DATABASE test_db;" -U postgres

install:
    - pecl channel-update pecl.php.net
    - yes | pecl install pcov
    - composer validate --ansi --no-interaction --strict
    - composer install --ansi --no-interaction --no-suggest
    - yarn install --frozen-lockfile --non-interactive --no-progress

before_script:
    - bin/console migrations:migrate --ansi --no-interaction
    - yarn dev

script:
    - yarn lint
    - vendor/bin/phpcs -ps
    - vendor/bin/phpstan analyse --ansi --no-progress
    - vendor/bin/psalm --no-progress --taint-analysis
    - vendor/bin/deptrac --ansi --fail-on-uncovered --no-interaction --no-progress
    - vendor/bin/phpunit --coverage-clover var/cache/clover.xml

after_success:
    - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
    - travis_retry php php-coveralls.phar -e test -x var/cache/clover.xml -o var/cache/coveralls.json
