dist: xenial
sudo: false
language: php

php:
    - '7.4'

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APP_ENV=test
        - SQL_MASTER=pgsql://postgres:@127.0.0.1:5432/test_db
        - SQL_SLAVES=pgsql://postgres:@127.0.0.1:5432/test_db
        - S3_ENDPOINT=http://127.0.0.1:9000
        - S3_KEY=minio
        - S3_SECRET=minio330
        - S3_REGION=test-region
        - S3_BUCKET=test-bucket

services:
    - docker
    - postgresql

before_install:
    - docker run --name minio -d
        -p 9000:9000
        -e MINIO_ACCESS_KEY=$S3_KEY
        -e MINIO_SECRET_KEY=$S3_SECRET
        -e MINIO_REGION=$S3_REGION
        minio/minio server /data
    - docker run --rm
        --network host
        --entrypoint sh
        minio/mc
        -c "
        mc config host add doop $S3_ENDPOINT $S3_KEY $S3_SECRET
        && mc mb --region $S3_REGION --ignore-existing doop/$S3_BUCKET
        && mc policy set download doop/$S3_BUCKET
        "
    - phpenv config-rm xdebug.ini

install:
    - pecl channel-update pecl.php.net
    - yes | pecl install pcov
    - composer validate --no-interaction --strict
    - composer install --no-interaction --no-suggest

before_script:
    - psql -c "CREATE DATABASE test_db;"
    - bin/console migrations:migrate --no-interaction

script:
    - vendor/bin/phpcs -ps
    - vendor/bin/phpstan analyse --no-progress
    - vendor/bin/psalm --no-progress
    - vendor/bin/phpunit --coverage-clover var/cache/clover.xml

after_success:
    - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - travis_retry php php-coveralls.phar -e test -x var/cache/clover.xml -o var/cache/coveralls.json
