version: '3'

networks:
    s3uploader:
        driver: bridge

services:
    nginx:
        depends_on:
            - php
        container_name: s3uploader-nginx
        image: nginx:1.15-alpine
        restart: ${DOCKER_RESTART}
        networks:
            - s3uploader
        volumes:
            - ./docker/nginx/s3.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:8080

    php:
        depends_on:
            - minio
            - mysql
        container_name: s3uploader-php
        build: docker/php
        restart: ${DOCKER_RESTART}
        networks:
            - s3uploader
        user: 1000:1000
        volumes:
            - .:/app:rw
        environment:
            XDEBUG_CONFIG: "remote_host=172.18.0.1 remote_port=9009"
            PHP_IDE_CONFIG: serverName=s3uploader

    mysql:
        container_name: s3uploader-mysql
        image: percona:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: ${DOCKER_RESTART}
        networks:
            - s3uploader
        ports:
            - 3306:3306
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'true'
            MYSQL_DATABASE: s3uploader
            MYSQL_USER: s3uploader
            MYSQL_PASSWORD: s3uploader

    minio:
        container_name: s3uploader-minio
        image: minio/minio:latest
        restart: ${DOCKER_RESTART}
        networks:
            - s3uploader
        ports:
            - 9000:9000
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio330
        command: server /data

    minio-create-bucket:
        depends_on:
            - minio
        container_name: s3uploader-minio-mc
        image: minio/mc:latest
        restart: ${DOCKER_RESTART}
        networks:
            - s3uploader
        entrypoint: >-
            sh -c "
                mc config host add s3uploader http://minio:9000 minio minio330;
                mc rm -r --force s3uploader/${S3_BUCKET};
                mc mb s3uploader/${S3_BUCKET};
                mc policy download s3uploader/${S3_BUCKET};
            "
