version: '3.4'

networks:
    doop:
        driver: bridge

services:
    nginx:
        depends_on:
            - php
        container_name: doop-nginx
        image: nginx:1.15-alpine
        restart: ${DOCKER_RESTART}
        networks:
            - doop
        volumes:
            - ./docker/nginx/doop.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:8080

    php:
        depends_on:
            - minio
            - minio-create-bucket
            - postgres
        container_name: doop-php
        build:
            context: docker/php
            target: development
        restart: ${DOCKER_RESTART}
        networks:
            - doop
        user: 1000:1000
        volumes:
            - .:/app:rw
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9009"
            PHP_IDE_CONFIG: serverName=doop

    postgres:
        container_name: doop-postgres
        image: postgres:11.3-alpine
        restart: ${DOCKER_RESTART}
        networks:
            - doop
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: doop
            POSTGRES_USER: doop
            POSTGRES_PASSWORD: doop
            POSTGRES_INITDB_ARGS: "--no-sync"

    minio:
        container_name: doop-minio
        image: minio/minio:latest
        restart: ${DOCKER_RESTART}
        networks:
            - doop
        ports:
            - 9000:9000
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio330
        command: server /data

    minio-create-bucket:
        depends_on:
            - minio
        container_name: doop-minio-mc
        image: minio/mc:latest
        restart: ${DOCKER_RESTART}
        networks:
            - doop
        entrypoint:
            - sh
            - -c
            - |-
                mc config host add doop http://minio:9000 minio minio330
                mc mb doop/${S3_BUCKET}
                mc policy set download doop/${S3_BUCKET}
