parameters:
    migrations_namespace: 'Radarlog\S3Uploader\Infrastructure\Sql\Migrations'
    migrations_dir_name: '%kernel.project_dir%/src/Infrastructure/Sql/Migrations'
    migrations_template: '%kernel.project_dir%/src/Infrastructure/Sql/Migrations/template.tmpl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\Migrations\Configuration\Configuration:
        arguments: ['@Radarlog\S3Uploader\Infrastructure\Sql\Connection']
        calls:
            - [setMigrationsNamespace, ['%migrations_namespace%']]
            - [setMigrationsDirectory, ['%migrations_dir_name%']]
            - [setCustomTemplate, ['%migrations_template%']]

    Doctrine\Migrations\Tools\Console\Command\:
        resource: '../vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command'
        exclude:
            - '../vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php'
        calls:
            - [setMigrationConfiguration, ['@Doctrine\Migrations\Configuration\Configuration']]
