parameters:
    migrations_namespace: 'Radarlog\Doop\Infrastructure\Sql\Migrations'
    migrations_dir_name: '%kernel.project_dir%/src/Infrastructure/Sql/Migrations'
    migrations_template: '%kernel.project_dir%/src/Infrastructure/Sql/Migrations/template.tmpl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\Migrations\Configuration\Connection\ExistingConnection:
        arguments: ['@Radarlog\Doop\Infrastructure\Sql\Connection']

    Doctrine\Migrations\Configuration\Migration\ConfigurationArray:
        arguments:
            -   custom_template: '%migrations_template%'
                migrations_paths:
                    '%migrations_namespace%': '%migrations_dir_name%'

    Doctrine\Migrations\DependencyFactory:
        factory: Doctrine\Migrations\DependencyFactory::fromConnection
        arguments:
            - '@Doctrine\Migrations\Configuration\Migration\ConfigurationArray'
            - '@Doctrine\Migrations\Configuration\Connection\ExistingConnection'

    Doctrine\Migrations\Tools\Console\Command\:
        resource: '../vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command'
        exclude:
            - '../vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php'
