index:
    path: /
    controller: Radarlog\Doop\Infrastructure\Http\Controller\Index
    methods: [GET]

upload:
    path: /upload
    controller: Radarlog\Doop\Infrastructure\Http\Controller\Upload
    methods: [POST]

image:
    path: /image/{uuid}
    requirements:
        uuid: !php/const Radarlog\Doop\Domain\Image\Uuid::REGEX
    controller: Radarlog\Doop\Infrastructure\Http\Controller\Image
    methods: [GET]

remove:
    path: /remove/{uuid}
    requirements:
        uuid: !php/const Radarlog\Doop\Domain\Image\Uuid::REGEX
    controller: Radarlog\Doop\Infrastructure\Http\Controller\Remove
    methods: [GET]
