index:
    path: /
    controller: Radarlog\S3Uploader\Infrastructure\Http\Controller\Index
    methods: [GET]

upload:
    path: /upload
    controller: Radarlog\S3Uploader\Infrastructure\Http\Controller\Upload
    methods: [POST]

image:
    path: /image/{hash}
    controller: Radarlog\S3Uploader\Infrastructure\Http\Controller\Image
    methods: [GET]
