imports:
    - { resource: 's3.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Radarlog\S3Uploader\:
        resource: '../src'
        exclude:
            - '../src/Kernel.php'
            - '../src/Infrastructure/S3/*'
