imports:
    - { resource: 'logs.yaml' }
    - { resource: 'migrations.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Radarlog\Doop\Application\Command\Handler:
            tags: ['command.handler']

    Radarlog\Doop\:
        resource: '../src'
        exclude:
            - '../src/Infrastructure/Kernel.php'
            - '../src/Infrastructure/Sql/Migrations'

    # Command Bus
    Radarlog\Doop\Application\Command\SimpleBus:
        arguments: [!tagged command.handler]
    Radarlog\Doop\Application\Command\LoggerBus:
        decorates: Radarlog\Doop\Application\Command\SimpleBus
        arguments: ['@monolog.logger.commands']
    Radarlog\Doop\Application\Command\Bus: '@Radarlog\Doop\Application\Command\LoggerBus'

    # S3
    Radarlog\Doop\Infrastructure\S3\Connection:
        arguments: ['%env(string:S3_DSN)%']
    Radarlog\Doop\Infrastructure\S3\Client:
        arguments: ['%env(string:S3_BUCKET)%', '%env(bool:S3_USE_PATH_STYLE)%']

    # SQL
    Radarlog\Doop\Infrastructure\Sql\Connection:
        factory: Radarlog\Doop\Infrastructure\Sql\ConnectionFactory::create
        arguments:
            -   master: '%env(string:SQL_MASTER)%'
                slaves: '%env(string:SQL_SLAVES)%'
