services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Radarlog\S3Uploader\:
        resource: '../src'

    # S3
    Radarlog\S3Uploader\Infrastructure\S3\Connection:
        arguments: ['%env(resolve:S3)%']
