imports:
    - { resource: 'logs.yaml' }
    - { resource: 'migrations.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Radarlog\S3Uploader\Application\Command\Handler:
            tags: ['command.handler']

    Radarlog\S3Uploader\:
        resource: '../src'
        exclude:
            - '../src/Kernel.php'
            - '../src/Infrastructure/MySql/Migrations'

    # Command Bus
    Radarlog\S3Uploader\Application\Command\SimpleBus:
        arguments: [!tagged command.handler]
    Radarlog\S3Uploader\Application\Command\LoggerBus:
        decorates: Radarlog\S3Uploader\Application\Command\SimpleBus
        arguments: ['@monolog.logger.commands']
    Radarlog\S3Uploader\Application\Command\Bus: '@Radarlog\S3Uploader\Application\Command\LoggerBus'

    # S3
    Radarlog\S3Uploader\Infrastructure\S3\Connection:
        arguments: ['%env(resolve:S3_DSN)%']
    Radarlog\S3Uploader\Infrastructure\S3\Client:
        arguments: ['%env(resolve:S3_BUCKET)%']

    # MySQL
    Radarlog\S3Uploader\Infrastructure\MySql\Connection:
        factory: Radarlog\S3Uploader\Infrastructure\MySql\ConnectionFactory::create
        arguments:
            -   master: '%env(resolve:MYSQL_MASTER)%'
                slaves: '%env(resolve:MYSQL_SLAVES)%'
