services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Radarlog\S3Uploader\Domain\Repository: '@Radarlog\S3Uploader\Infrastructure\MySql\PersistenceRepository'
