services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.repository: '@Radarlog\S3Uploader\Domain\Repository'
    test.query.all: '@Radarlog\S3Uploader\Application\Query\Image\FindAll'
    test.query.one: '@Radarlog\S3Uploader\Application\Query\Image\FindOne'
