imports:
    - { resource: 'logs.yaml' }
    - { resource: 'migrations.yaml' }

parameters:
    container.dumper.inline_factories: true
    container.dumper.inline_class_loader: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Radarlog\Doop\Application\Command\Handler:
            tags: ['command.handler']
        Radarlog\Doop\Infrastructure\Http\Controller:
            bind:
                Radarlog\Doop\Application\Command\Bus: '@Radarlog\Doop\Infrastructure\Http\ThrowableHandlerBus'
        Radarlog\Doop\Infrastructure\Cli\Executable:
            bind:
                Radarlog\Doop\Application\Command\Bus: '@Radarlog\Doop\Infrastructure\Logger\Bus'

    Radarlog\Doop\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Kernel.php'
            - '../src/Infrastructure/Sql/Migrations'

    # Command Bus
    Radarlog\Doop\Application\Command\SimpleBus:
        arguments: [ !tagged command.handler ]
    Radarlog\Doop\Infrastructure\Logger\Bus:
        decorates: Radarlog\Doop\Application\Command\SimpleBus
        arguments: [ '@monolog.logger.commands' ]
    Radarlog\Doop\Infrastructure\Http\ThrowableHandlerBus:
        decorates: Radarlog\Doop\Infrastructure\Logger\Bus

    Symfony\Component\HttpFoundation\Session\Flash\FlashBag: ~
    Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface:
        alias: Symfony\Component\HttpFoundation\Session\Flash\FlashBag

    # S3
    Radarlog\Doop\Infrastructure\S3\Connection:
        factory: Radarlog\Doop\Infrastructure\S3\Connection::fromDsn
        arguments: [ '%env(string:S3_DSN)%' ]
    Radarlog\Doop\Infrastructure\S3\Client:
        arguments: ['%env(string:S3_BUCKET)%']

    # SQL
    Radarlog\Doop\Infrastructure\Sql\Connection:
        factory: Radarlog\Doop\Infrastructure\Sql\ConnectionFactory::create
        arguments:
            $primaryDsn: '%env(string:SQL_PRIMARY_DSN)%'
            $replicaDsn: '%env(string:SQL_REPLICA_DSN)%'
