name: CI

on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        paths-ignore:
            - '**.md'

jobs:
    tests:
        name: PHP ${{ matrix.php }} tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-20.04
                php:
                    - 8.0
                experimental: [ false ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Build docker-compose stack
                run: docker-compose up -d

            -   name: Check running containers
                run: docker-compose ps

            -   name: Install composer dependencies
                run: |
                    docker-compose exec -T php composer validate --ansi --no-interaction --strict
                    docker-compose exec -T php composer check-platform-reqs --ansi --no-dev --no-interaction
                    docker-compose exec -T php composer install --ansi --no-interaction
                    docker-compose exec -T php composer normalize --ansi --dry-run --no-interaction

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov

            -   name: Install composer dependencies
                run: |
                    composer validate --ansi --no-interaction --strict
                    composer install --ansi --no-interaction
                    composer normalize --ansi --dry-run --no-interaction

            -   name: Check Coding standards
                run: vendor/bin/phpcs

            -   name: Run PHPStan
                run: vendor/bin/phpstan analyse --ansi

            -   name: Run Psalm
                run: vendor/bin/psalm --taint-analysis --output-format=github

            -   name: Run Deptrac
                run: vendor/bin/deptrac --ansi --fail-on-uncovered --no-interaction
