name: CI

on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        paths-ignore:
            - '**.md'

jobs:
    tests:
        name: PHP ${{ matrix.php }} tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-18.04
                    - ubuntu-20.04
                php:
                    - 8.1
                experimental: [ false ]

        env:
            MYUID: 1001
            MYGID: 121
            COMPOSER_CACHE_DIR: /app/.composer/

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   uses: satackey/action-docker-layer-caching@v0.0.11
                continue-on-error: true

            -   name: Install frontend dependencies
                run: docker-compose run -T --rm encore yarn install --frozen-lockfile --non-interactive

            -   name: Build docker-compose stack
                run: |
                    docker-compose build --build-arg MYUID=$MYUID --build-arg MYGID=$MYGID php
                    docker-compose up -d
                    docker-compose ps

            -   uses: actions/cache@v3
                with:
                    path: $COMPOSER_CACHE_DIR
                    key: ${{ matrix.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ matrix.os }}-${{ matrix.php }}-composer-

            -   name: Install composer dependencies
                run: |
                    echo $COMPOSER_CACHE_DIR
                    ls -lla
                    docker-compose exec -T php composer validate --ansi --no-interaction --strict
                    docker-compose exec -T php composer check-platform-reqs --ansi --no-dev --no-interaction
                    docker-compose exec -T php composer install --ansi --no-interaction
                    docker-compose exec -T php composer normalize --ansi --dry-run --no-interaction
                    ls -lla

            -   name: Run migrations
                run: docker-compose exec -T -e APP_ENV=test php bin/console migrations:migrate --ansi --allow-no-migration --no-interaction

            -   name: Check Coding Standards
                run: |
                    docker-compose exec -T php vendor/bin/phpcs
                    docker-compose exec -T encore yarn lint

            -   name: Run PHPStan
                run: docker-compose exec -T php vendor/bin/phpstan analyse --ansi

            -   name: Run Psalm
                run: docker-compose exec -T php vendor/bin/psalm --output-format=github

            -   name: Run Deptrac
                run: docker-compose exec -T php vendor/bin/deptrac --ansi --fail-on-uncovered --no-interaction

            -   name: Run PHPUnit
                run: docker-compose exec -T php vendor/bin/phpunit --coverage-clover var/cache/clover.xml

            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v2
                with:
                    files: var/cache/clover.xml
                    verbose: true
